# -*- coding: utf-8 -*-
"""emedd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LQhztY04cM68rHtePPzmDl3OrkueaUgo
"""

from sentence_transformers import SentenceTransformer

# Load the model
model = SentenceTransformer("Qwen/Qwen3-Embedding-0.6B")


queries = [
    "What is the capital of China?",
    "Explain gravity",
]
documents = [
    "The capital of China is Beijing.",
    "Gravity is a force that attracts two bodies towards each other. It gives weight to physical objects and is responsible for the movement of planets around the sun.",
]


query_embeddings = model.encode(queries, prompt_name="query")
document_embeddings = model.encode(documents)


similarity = model.similarity(query_embeddings, document_embeddings)
print(similarity)

from google import genai
from google.colab import userdata

client = genai.Client(api_key=userdata.get('GEMINI_API_KEY'))

result = client.models.embed_content(
        model="gemini-embedding-001",
        contents="What is the meaning of life?"
)

print(result.embeddings)

from google import genai

client = genai.Client(api_key=userdata.get('GEMINI_API_KEY'))

result = client.models.embed_content(
    model="gemini-embedding-001",
    contents=[
            "What is the meaning of life?",
            "What is the purpose of existence?",
            "How do I bake a cake?"
    ]
)
for embedding in result.embeddings:
  print(embedding)

from google import genai
from google.genai import types
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

client = genai.Client(api_key=userdata.get('GEMINI_API_KEY'))

texts = [
    "What is the meaning of life?",
    "What is the purpose of existence?",
    "How do I bake a cake?",
]

result = client.models.embed_content(
    model="gemini-embedding-001",
    contents=texts,
    config=types.EmbedContentConfig(task_type="SEMANTIC_SIMILARITY")
)


df = pd.DataFrame(
    cosine_similarity([e.values for e in result.embeddings]),
    index=texts,
    columns=texts,
)

print(df)