# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P92xKEgcauzvENZtgq-7OD4A5n9OxJYi
"""

from huggingface_hub import notebook_login

notebook_login()

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch


model_name = "meta-llama/Llama-2-7b-chat-hf"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map='auto'
)

prompt = "Explain quantum computing in simple terms."

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

output = model.generate(
    **inputs,
    max_new_tokens=150,
    temperature=0.7,
    top_p=0.9,
    do_sample=True
)
print(tokenizer.decode(output[0], skip_special_tokens=True))

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"


tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

model.eval()

prompt = "Explain artificial intelligence simply."


input_ids = tokenizer(prompt, return_tensors="pt").input_ids


with torch.no_grad():
    output_ids = model.generate(
        input_ids,
        max_new_tokens=100
    )


output_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)

print(output_text)

max_new_tokens= 50
generated = input_ids

model.eval()

with torch.no_grad():
  for _ in range(max_new_tokens):

      outputs = model(generated)

      next_token_logits = outputs.logits[:, -1, :]
      #(batch_size, sequence_length, vocab_size)
      #(1,12,32000)

      #convert to probabilities
      probs = torch.softmax(next_token_logits, dim=-1)

      next_token = torch.multinomial(probs, num_samples=1)

      generated = torch.cat([generated, next_token], dim=1)

text = tokenizer.decode(generated[0], skip_special_token=True)

#tokens → embeddings → attention layers → logits