# -*- coding: utf-8 -*-
"""pytorch inf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11QWAynqv1JG6tVGDaYo7hadWbMvidGcy
"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

device = "cuda" if torch.cuda.is_available() else "cpu"
tokenizer = AutoTokenizer.from_pretrained("gpt2")

model = AutoModelForCausalLM.from_pretrained(
    "gpt2",
    torch_dtype=torch.float16
)

model = model.to(device)

model.eval()

inputs = tokenizer(
    "Explain the transformer in simple terms",
    return_tensors="pt"
)

inputs = {k:v.to(device) for k,v in inputs.items()}

with torch.inference_mode():

  outputs = model(**inputs)

  logits = outputs.logits

  probs = torch.softmax(logits[:,-1,:], dim=-1)

  next_token = torch.argmax(probs, dim=-1)

  print("Next token ID:", next_token.item())


  generated_ids = model.generate(
      **inputs,
      max_new_tokens=50
  )

  response = tokenizer.decode(
      generated_ids[0],
      skip_special_tokens=True
  )

  print(response)

  torch.cuda.empty_cache()

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "gpt2"

device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.float16 if device == "cuda" else torch.float32

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=dtype
).to(device)

model.eval()


if device == "cuda":
    model = torch.compile(model, mode="reduce-overhead")

prompts = [
    "Explain attention in transformers simply.",
    "What is LLM inference?",
    "Why do we use GPUs for deep learning?"
]

inputs = tokenizer(
    prompts,
    return_tensors="pt",
    padding=True,
    truncation=True
)

inputs = {k: v.to(device) for k, v in inputs.items()}

with torch.inference_mode():
    generated_ids = model.generate(
        **inputs,
        max_new_tokens=60,
        do_sample=True,
        temperature=0.7,
        top_p=0.9,
        pad_token_id=tokenizer.eos_token_id
    )

responses = tokenizer.batch_decode(
    generated_ids,
    skip_special_tokens=True
)

for i, response in enumerate(responses, 1):
    print(f"\nResponse {i}:\n{response}")

if device == "cuda":
    torch.cuda.empty_cache()

"""# distributed training

from torch.nn.parallel import DistributedDataParallel as DDP

model = DDP(model, device_ids=[local_rank])
"""