# -*- coding: utf-8 -*-
"""slm3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RW1lod5bDu6edcZ9q5KakR8HZltctdK9
"""

pip install -U transformers accelerate bitsandbytes

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_id = "google/gemma-2b-it"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto"
)

prompt = "Write a polite email declining a meeting."
inputs = tokenizer(prompt, return_tensors="pt")

# Move input tensors to the model's device
inputs = {k: v.to(model.device) for k, v in inputs.items()}

output = model.generate(**inputs, max_new_tokens=120)
print(tokenizer.decode(output[0], skip_special_tokens=True))