# -*- coding: utf-8 -*-
"""standard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Na6sJrlJTYlVDO5Kca240S4a01JIpBOj
"""

!pip install -q transformers peft bitsandbytes accelerate

import torch
import bitsandbytes as bnb
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, TaskType


MODEL_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

print(f"GPU: {torch.cuda.get_device_name(0)}")
print(f"VRAM : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)


model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

print(f"VRAM used: {torch.cuda.memory_allocated() / 1e9:.2f} GB")


w = model.model.layers[0].self_attn.q_proj.weight
print(f"Weight dtype (stored) : {w.dtype}")

model = prepare_model_for_kbit_training(model)
model.config.use_cache = False

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    bias="none",
    task_type=TaskType.CAUSAL_LM,
)
model = get_peft_model(model, lora_config)


total     = sum(p.numel() for p in model.parameters())
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
frozen    = total - trainable

print(f"Total     : {total / 1e6:.1f}M")
print(f"Trainable : {trainable / 1e6:.1f}M  ({100 * trainable / total:.3f}%)   LoRA adapters BF16")
print(f"Frozen    : {frozen / 1e6:.1f}M   4-bit base")


for name, param in model.named_parameters():
    if param.requires_grad:
        param.data = param.data.to(torch.bfloat16)


for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"Adapter dtype : {param.dtype}")
        break