# -*- coding: utf-8 -*-
"""synthetic data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jBxD7nbDHqMI3XhTI_ogGOGilFqc8-ec
"""

!pip install deepeval chromadb langchain langchain_community langchain_text_splitters

import os
from google.colab import userdata
os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")

from deepeval.synthesizer import Synthesizer

synthesizer = Synthesizer()
goldens = synthesizer.generate_goldens_from_docs(
    document_paths=['sentiment.txt'], # Replace with your file
    include_expected_output=True
)
print(goldens)

dataframe = synthesizer.to_pandas()
print(dataframe)

#getting actual output from llm around the golden dataset
# from openai import OpenAI
# client = OpenAI()

# for g in goldens:
#   response = client.chat.completions.create(
#       model="gpt-4o-mini",
#       messages=[{"role": "user", "content": g.input}]
#   )
#   g.actual_output = response.choices[0].message.content

from openai import OpenAI
client=OpenAI()

for g in goldens:
  prompt = f"""
You are given labeled customer reviews below.

Context:
{g.context}

Answer the following question strictly using the context.
Return only the final answer. Do not explain.

Question:
{g.input}
"""

  response = client.chat.completions.create(
      model="gpt-4o-mini",
      messages=[{"role": "user", "content": prompt}] # Changed 'context' to 'content'
  )

  g.actual_output = response.choices[0].message.content.strip()

df = synthesizer.to_pandas()
df.head()

#converting to test cases
from deepeval.test_case import LLMTestCase

test_cases = [
    LLMTestCase(
        input=g.input,
        actual_output=g.actual_output,
        expected_output=g.expected_output,
        context=g.context
    )
    for g in goldens
]

#metric

from deepeval.metrics import GEval
from deepeval import evaluate
from deepeval.test_case import LLMTestCaseParams

correctness_metric = GEval(
    name="Correctness",
    criteria="Determine whether the actual output matches the expected output exactly for sentiment classification (positive, negative, neutral)",
    evaluation_params=[
        LLMTestCaseParams.INPUT,
        LLMTestCaseParams.ACTUAL_OUTPUT,
        LLMTestCaseParams.EXPECTED_OUTPUT
    ]
)

evaluate(test_cases=test_cases, metrics=[correctness_metric])

from deepeval.test_case import LLMTestCase

reviews = [
    ("I absolutely love this product. It exceeded my expectations.", "positive"),
    ("This is the worst experience I've ever had.", "negative"),
    ("The service was okay, nothing special.", "neutral"),
    ("I'm extremely happy with the results!", "positive"),
    ("The package arrived late and damaged.", "negative"),
    ("It works as intended.", "neutral"),
    ("Fantastic quality and fast shipping!", "positive"),
    ("I'm very disappointed with the customer support.", "negative"),
    ("The product is fine for the price.", "neutral"),
    ("This app makes my life so much easier.", "positive"),
    ("I regret buying this.", "negative"),
    ("The update didn’t change much.", "neutral"),
    ("Absolutely amazing experience from start to finish.", "positive"),
    ("It stopped working after two days.", "negative"),
    ("The design is simple and clean.", "neutral"),
    ("Best purchase I've made this year!", "positive"),
    ("Total waste of money.", "negative"),
    ("It’s neither good nor bad.", "neutral"),
    ("Customer service was incredibly helpful.", "positive"),
    ("I'm frustrated with the constant crashes.", "negative"),
]

test_cases = [
    LLMTestCase(
        input=text,
        actual_output="",
        expected_output=label
    )
    for text, label in reviews
]

from openai import OpenAI
client = OpenAI()

for test_case in test_cases:
    prompt = f"""
Classify the sentiment of the following text.

Return ONLY one word:
positive
negative
neutral

Text:
{test_case.input}
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    test_case.actual_output = response.choices[0].message.content.strip().lower()

from deepeval.metrics import GEval
from deepeval import evaluate

classification_metric = GEval(
    name="Sentiment Classification Accuracy",
    criteria="Determine whether the predicted sentiment exactly matches the expected sentiment label.",
    evaluation_params=["actual_output", "expected_output"]
)

evaluate(test_cases=test_cases, metrics=[correctness_metric])