# -*- coding: utf-8 -*-
"""vlm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZU-I9FW5ZcsFt-r8PCX6S4WC1-wp4UN
"""

!pip install git+https://github.com/huggingface/transformers -q
!pip install paddlepaddle paddleocr -q
!pip install accelerate bitsandbytes -q
!pip install datasets pydantic pillow -q
!pip install langchain-text-splitters -q

import json
import re
import numpy as np
import torch
from PIL import Image
from datasets import load_dataset
from paddleocr import PaddleOCR
from transformers import Qwen3VLForConditionalGeneration, AutoProcessor
from pydantic import BaseModel, field_validator, ValidationError
from typing import Optional

dataset = load_dataset(
    "naver-clova-ix/cord-v2",
    split="test",
    streaming=True
)

sample = next(iter(dataset))

image = sample["image"]
ground_truth = json.loads(sample["ground_truth"])
print("Image size:", image.size)
print("\nGround truth (gt_parse):")
print(json.dumps(ground_truth["gt_parse"], indent=2))

image

model_id = "Qwen/Qwen3-VL-2B-Instruct"
processor = AutoProcessor.from_pretrained(model_id)
model = Qwen3VLForConditionalGeneration.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16,
    device_map="auto",
)
model.eval()
print("Model loaded!")

class MenuItem(BaseModel):
    nm: str
    cnt: Optional[str] = None
    price: Optional[str] = None

class SubTotal(BaseModel):
    subtotal_price: Optional[str] = None
    service_price: Optional[str] = None
    tax_price: Optional[str] = None
    etc: Optional[str] = None

class Total(BaseModel):
    total_price: Optional[str] = None

class ReceiptOutput(BaseModel):
    menu: list[MenuItem]
    sub_total: Optional[SubTotal] = None
    total: Optional[Total] = None

    @field_validator("menu")
    @classmethod
    def menu_not_empty(cls, v):
        assert len(v) > 0, "Menu must have at least one item"
        return v

def run_vlm(pil_image):
    prompt = """You are a receipt parser. Look at this receipt image carefully.
Extract every menu item, subtotal, and total.
Return ONLY valid JSON, no explanation, no markdown backticks:
{
  "menu": [
    {"nm": "item name", "cnt": "1 x", "price": "75,000"}
  ],
  "sub_total": {
    "subtotal_price": "...",
    "service_price": "...",
    "tax_price": "...",
    "etc": "..."
  },
  "total": {
    "total_price": "..."
  }
}"""

    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": pil_image},
                {"type": "text", "text": prompt}
            ]
        }
    ]

    inputs = processor.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_dict=True,
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=1024,
            do_sample=False
        )

    trimmed = output_ids[0][inputs["input_ids"].shape[1]:]
    return processor.decode(trimmed, skip_special_tokens=True)

def extract_json(raw_text):
  raw_text = re.sub(r"```json|```", "", raw_text).strip()
  match = re.search(r"\{.*\}", raw_text, re.DOTALL)
  if match:
    return match.group()
  return None

def evaluate(pred: ReceiptOutput, gt: dict):
    gt_parse = gt["gt_parse"]
    gt_items = gt_parse.get("menu", [])

    print("\n" + "="*50)
    print("RESULTS")
    print("="*50)


    print(f"\nMenu items → Predicted: {len(pred.menu)} | GT: {len(gt_items)}")

    print("\nPredicted:")
    for item in pred.menu:
        print(f"  {item.nm:30s} {str(item.cnt):8s} {item.price}")

    print("\nGround Truth:")
    for item in gt_items:
        print(f"  {item['nm']:30s} {str(item.get('cnt')):8s} {item.get('price')}")


    gt_names = [i["nm"].lower().strip() for i in gt_items]
    pred_names = [i.nm.lower().strip() for i in pred.menu]
    matched = sum(1 for p in pred_names if any(p in g or g in p for g in gt_names))
    name_score = matched / max(len(gt_names), 1)

    gt_total = gt_parse.get("total", {}).get("total_price", "N/A")
    pred_total = pred.total.total_price if pred.total else "N/A"

    print(f"\nName match:  {matched}/{len(gt_names)} = {name_score:.0%}")
    print(f"Total price: Predicted={pred_total} | GT={gt_total} | {'✅' if gt_total == pred_total else '❌'}")

    return {"name_score": name_score, "total_match": gt_total == pred_total}

print("Running Qwen3-VL-2B on receipt image...")
raw_output = run_vlm(image)
print(f"\nRaw output:\n{raw_output}")

json_str = extract_json(raw_output)
if not json_str:  print('No valid JSON found in the output.')
else:
  try:
        validated = ReceiptOutput(**json.loads(json_str))
        print("\n Pydantic validation passed!")

        # Create a mutable copy of ground_truth to modify for evaluation
        temp_ground_truth = ground_truth.copy()
        if "gt_parse" in temp_ground_truth and "menu" in temp_ground_truth["gt_parse"]:
            gt_menu_data = temp_ground_truth["gt_parse"]["menu"]
            if isinstance(gt_menu_data, dict):
                temp_ground_truth["gt_parse"]["menu"] = [gt_menu_data]

        scores = evaluate(validated, temp_ground_truth)
  except (ValidationError, json.JSONDecodeError) as e:
        print(f"\n Validation failed: {e}")
        print(f"Raw JSON:\n{json_str}")

def normalize_price(price_str):
    if not price_str:
        return ""
    price_str = price_str.strip().lstrip("-")
    price_str = price_str.replace(".", "").replace(",", "")
    return price_str

def evaluate_normalized(pred: ReceiptOutput, gt: dict):
    gt_parse = gt["gt_parse"]
    gt_items = gt_parse.get("menu", [])

    gt_names = [i["nm"].lower().strip().lstrip("-") for i in gt_items]
    pred_names = [i.nm.lower().strip().lstrip("-") for i in pred.menu]
    matched = sum(1 for p in pred_names if any(p in g or g in p for g in gt_names))
    name_score = matched / max(len(gt_names), 1)


    gt_total = gt_parse.get("total", {}).get("total_price", "")
    pred_total = pred.total.total_price if pred.total else ""
    total_match = normalize_price(gt_total) == normalize_price(pred_total)


    count_match = len(pred.menu) == len(gt_items)

    return {
        "name_score": name_score,
        "total_match": total_match,
        "count_match": count_match,
        "pred_items": len(pred.menu),
        "gt_items": len(gt_items)
    }

def run_on_samples(n=5):

    stream = load_dataset(
        "naver-clova-ix/cord-v2",
        split="test",
        streaming=True
    )

    results = []
    failed = []

    for i, sample in enumerate(stream):
        if i >= n:
            break

        print(f"\n{'='*50}")
        print(f"Sample {i+1}/{n}")
        print(f"{'='*50}")

        image = sample["image"]
        ground_truth = json.loads(sample["ground_truth"])


        temp_ground_truth = ground_truth.copy()
        if "gt_parse" in temp_ground_truth and "menu" in temp_ground_truth["gt_parse"]:
            gt_menu_data = temp_ground_truth["gt_parse"]["menu"]
            if isinstance(gt_menu_data, dict):
                temp_ground_truth["gt_parse"]["menu"] = [gt_menu_data]

        gt_parse = temp_ground_truth["gt_parse"]


        gt_items = gt_parse.get("menu", [])
        gt_total = gt_parse.get("total", {}).get("total_price", "N/A")
        print(f"GT: {len(gt_items)} items | total: {gt_total}")


        try:
            raw_output = run_vlm(image)
            json_str = extract_json(raw_output)

            if not json_str:
                print(" No JSON extracted")
                failed.append(i)
                continue

            validated = ReceiptOutput(**json.loads(json_str))
            scores = evaluate_normalized(validated, temp_ground_truth)

            pred_total = validated.total.total_price if validated.total else "N/A"
            print(f"Pred: {scores['pred_items']} items | total: {pred_total}")
            print(f"Name match: {scores['name_score']:.0%} | "
                  f"Count match: {'Match' if scores['count_match'] else 'Unmatch'} | "
                  f"Total match: {'Match' if scores['total_match'] else 'Unmatch'}")

            results.append(scores)

        except (ValidationError, json.JSONDecodeError) as e:
            print(f" Failed: {e}")
            failed.append(i)


    if results:
        avg_name = sum(r["name_score"] for r in results) / len(results)
        total_matches = sum(1 for r in results if r["total_match"])
        count_matches = sum(1 for r in results if r["count_match"])

        print(f"\n{'='*50}")
        print(f"SUMMARY — {len(results)} samples processed, {len(failed)} failed")
        print(f"{'='*50}")
        print(f"Avg name match score : {avg_name:.0%}")
        print(f"Total price match    : {total_matches}/{len(results)}")
        print(f"Item count match     : {count_matches}/{len(results)}")

# Run on 5 samples first
run_on_samples(n=5)